name: outages-per-geography

on:
  workflow_dispatch:
  schedule:
  #- cron: '*/12 * * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: ./scrape.py
    - run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git checkout --orphan latest-commit
        git add -A
        git commit -m "$(date -u)"
        git push origin latest-commit:main --force
